# .github/workflows/github-actions.yaml
name: Run main.py

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found; skipping."
          fi

      - name: Find and run main.py
        run: |
          # try to find main.py in the repo
          MAIN=$(find . -maxdepth 3 -type f -name main.py | head -n1)
          if [ -z "$MAIN" ]; then
            echo "❌ main.py not found — here’s the full file tree:" 
            ls -R .
            exit 1
          fi
          echo "✅ Found main.py at $MAIN"
          python "$MAIN"
